version: 2
jobs:
  build:
    docker:
      - image: swift:5.0
    steps:
      - checkout
      - run:
          name: Remove `main.swift` if built on Linux
          command: |
            if [[ $(uname -s) == Linux ]]; then
              rm Sources/SwiftlyRCC/main.swift
            fi
      - run:
          name: Build project
          command: |
            swift build
