aliases:
  - &git_checkout
    name: Checkout
    command: |
      mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      git clone --depth 1 -b $CIRCLE_BRANCH $CIRCLE_REPOSITORY_URL ./ && \
      git reset --hard $CIRCLE_SHA1
  - &adapt_for_linux
    name: Remove `main.swift` if built on Linux
    command: |
      if [[ $(uname -s) == Linux ]]; then
        rm Sources/SwiftlyRCC/main.swift
      fi
  - &build
    name: Build project
    command: |
      swift build
  - &docker_worker
    - image: swift:5.1
version: 2.1
jobs:
  build:
    docker: *docker_worker
    steps:
      - run: *git_checkout
      - run: *adapt_for_linux
      - run: *build
