version: 2
jobs:
  build:
    docker:
      - image: swift:5.0
    steps:
      - checkout
      - run:
          name: Remove `main.swift`
          command: rm Sources/SwiftlyRCC/main.swift
      - run:
          name: Build project
          command: |
            swift build
