version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt update && apt install --yes clang libcurl3 libpython2.7 libpython2.7-dev wget
      - run:
          name: Install swift
          command: |
            wget https://swift.org/builds/swift-4.2.1-release/ubuntu1804/swift-4.2.1-RELEASE/swift-4.2.1-RELEASE-ubuntu18.04.tar.gz && \
            tar xzf swift-4.2.1-RELEASE-ubuntu18.04.tar.gz && \
            mv swift-4.2.1-RELEASE-ubuntu18.04 /opt/swift && \
            export PATH=/opt/swift/usr/bin:$PATH && \
            ls -lia /opt/swift/usr/bin && \
            echo $PATH && \
            source  ~/.bashrc
      - run: echo "Debug step" && ls -lia && pwd
      - run:
          name: Run main.swift
          command: swift main.swift
