version: 2
jobs:
  build:
    docker:
      - image: swift:5.0
    steps:
      - checkout
      - run:
          name: Remove `main.swift` if built on Linux
          command: (/etc/os-release -a && rm Sources/SwiftlyRCC/main.swift) || true
      - run:
          name: Build project
          command: |
            swift build
