version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt update && apt install clang libcurl3 libpython2.7 libpython2.7-dev 
      - run:
          name: Install swift
          command: |
            wget https://swift.org/builds/swift-4.2.1-release/ubuntu1804/swift-4.2.1-RELEASE/swift-4.2.1-RELEASE-ubuntu18.04.tar.gz && \
            tar xzf swift-4.2.1-RELEASE-ubuntu18.04.tar.gz && \
            sudo mv swift-4.2.1-RELEASE-ubuntu18.04 /opt/swift && \
            echo "export PATH=/opt/swift/swift/usr/bin:$PATH" >> ~/.bashrc && \
            source  ~/.bashrc
      - run:
          name: Building main.swift
          command: swiftc main.swift
