version: 2
jobs:
  build:
    docker:
        - image: ubuntu:18.04
    environment:
      BASH_ENV: /etc/bash.bashrc
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt update && apt install --yes clang libcurl3 libpython2.7 libpython2.7-dev wget
      - run:
          name: Install swift
          command: |
            wget https://swift.org/builds/swift-4.2.1-release/ubuntu1804/swift-4.2.1-RELEASE/swift-4.2.1-RELEASE-ubuntu18.04.tar.gz && \
            tar xzf swift-4.2.1-RELEASE-ubuntu18.04.tar.gz && \
            mv swift-4.2.1-RELEASE-ubuntu18.04 /usr/share/swift && \
            echo 'export PATH=/usr/share/swift/usr/bin:"${PATH}"' >> $BASH_ENV
      - run: echo $BASH_ENV && echo "Debug step" && ls -lia && pwd && echo $PATH && ls /usr/share/swift/usr/bin -lia
      - run:
          name: Run main.swift
          command: swift --version && SwiftlyRCC/main.swift
