version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install swift dependencies
          command: apt update && apt install swiftc --yes
      - run:
          name: Building main.swift
          command: swiftc main.swift
